### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by appgurueu** [spiraling-down/game#1]
- [x] nodes
  - [x] basic registrations
  - [x] crumbling
  - [x] plate drawtype
  - [x] ores
- [ ] worldgen
  - [x] basic layered worldgen, where layers use perlin noise for transition
  - [x] actual layer style
  - [x] decos
  - [x] ores
  - [ ] inclusions
- [x] gui/hud
  - [x] basic story telling framework
    - [x] fade-out blackscreen
    - [x] animated text writing
- [ ] threats
  - [ ] turrets
  - [x] small mobs
- [x] beacons
- [ ] events
- [ ] artifacts
- [ ] plot/story
- [ ] particles and advanced graphics
  - [ ] player model
  - [ ] sound effects
- [ ] misc
  - [ ] determine good default settings for the game and set them
- [x] disable various built-in commands
